# Generated by Django 4.1.7 on 2023-03-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='costummer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_p', models.ImageField(upload_to='profile_p')),
            ],
        ),
    ]
