# Generated by Django 4.1.7 on 2023-03-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kick', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='costummer',
        ),
    ]
