# Generated by Django 4.1.7 on 2023-03-19 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kick', '0002_delete_costummer'),
    ]

    operations = [
        migrations.CreateModel(
            name='costummer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('profile_p', models.ImageField(upload_to='profile_p')),
                ('is_cos', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True)),
                ('sex', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
