# Generated by Django 4.1.7 on 2023-03-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kick', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costummer',
            old_name='is_cos',
            new_name='cos',
        ),
    ]
